apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicdtest
  namespace: cicd
  labels:
    app: cicd
spec:
  replicas: 4
  selector:
    matchLabels:
      app: cicd
  template:
    metadata:
      labels:
        app: cicd
    spec:
      containers:
        - name: cicdtest
          image: grandeur.azurecr.io/cicd:1.0
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: grandeur
      imagePullPolicy: Always